services:
  client:
    container_name: client
    build:
      context: ./
    ports:
      - '${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}'
    volumes:
      - client_build:/app/build

volumes:
  client_build:
