services:
  client:
    container_name: client
    build:
      context: ./
    ports:
      - '${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}'
    volumes:
      - client_build:/app/build

  caddy:
    container_name: caddy-client
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - client_build:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client

volumes:
  client_build:
  caddy_data:
  caddy_config:
